#嵌入式服务器配置
server:
  port: 8086

  tomcat:
    uri-encoding: UTF-8

  undertow:
    accesslog:
      # Undertow access log directory.
      dir: ./logs
      # Enable access log.
      enabled: false
      # Format pattern for access logs.
      pattern: common
      # Log file name prefix.
      prefix: access_log
      # Enable access log rotation.
      rotate: true
      # Log file name suffix.
      suffix: log

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    #参数配置，显示sql
    props:
      sql:
        show: true
    #配置数据源
    datasource:
      #给每个数据源去别名，下面的ds1，ds2任意取名
      names: ds1,ds2
      #给master-ds1每个数据源配置数据库连接信息
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/webchat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8
        username: root
        password: root
        maxPoolSize: 100
        miniPoolSize: 5
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/webchat1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8
        username: root
        password: root
        maxPoolSize: 100
        miniPoolSize: 5

    #配置默认写入的操作
    sharding:
    #配置默认数据源，主要用来写入，如果不配置，此时三个节点都会被当成从节点，新增/修改/删除时候会报错
      default-data-source-name: ds1

    # 配置数据源的读写分离，但数据库一定要做主从复制
      master-slave-rules:
        ds1:
          master-data-source-name: ds1 # 主库数据源名称
          slave-data-source-names: ds2 # 从库数据源名称列表

